// app/utils/quotesDatabase.js

export const MOTIVATIONAL_QUOTES = [
  // âš½ FOOTBALLERS
  { player: "Cristiano Ronaldo", quote: "Your love makes me strong, your hate makes me unstoppable.", category: "football" },
  { player: "Lionel Messi", quote: "You have to fight to reach your dream. You have to sacrifice and work hard for it.", category: "football" },
  { player: "Mohamed Salah", quote: "I'm not here to talk about the past. I'm here to win.", category: "football" },
  { player: "Virgil van Dijk", quote: "Confidence comes from preparation. Train like you play.", category: "football" },
  { player: "Sam Kerr", quote: "Believe in yourself even when no one else does. That's when magic happens.", category: "football" },
  { player: "Kylian MbappÃ©", quote: "Speed is nothing without direction. Know your goal.", category: "football" },
  { player: "Megan Rapinoe", quote: "Be louder than your fear. The pitch is your stage.", category: "football" },
  { player: "Erling Haaland", quote: "Goals don't come from wishing. They come from working.", category: "football" },
  { player: "Alex Morgan", quote: "Success is earned, not given. Every day is a chance to improve.", category: "football" },
  { player: "Neymar Jr", quote: "Creativity is the weapon. Technique is the ammunition.", category: "football" },
  { player: "Lucy Bronze", quote: "Hard work beats talent when talent doesn't work hard.", category: "football" },
  { player: "Ronaldinho", quote: "Enjoy the game. Smile, have fun, and let your feet do the talking.", category: "football" },
  { player: "Marta", quote: "I play for the girls who dream big. Never give up on your dreams.", category: "football" },
  { player: "Zinedine Zidane", quote: "Elegance is not about showing off. It's about making it look easy.", category: "football" },
  { player: "Abby Wambach", quote: "Failure is fuel. Use it to burn brighter.", category: "football" },
  { player: "Thierry Henry", quote: "The ball is round, but the game is square. Anything can happen.", category: "football" },
  { player: "Ada Hegerberg", quote: "I don't play to be second. I play to win everything.", category: "football" },
  { player: "AndrÃ©s Iniesta", quote: "The best pass is the one before the goal. Patience wins games.", category: "football" },
  { player: "Serena Williams", quote: "I'm not afraid of failure. I'm afraid of not trying.", category: "tennis" },
  { player: "Roger Federer", quote: "Doubt kills more dreams than failure ever will.", category: "tennis" },
  { player: "Rafael Nadal", quote: "Every point is a battle. Every match is a war.", category: "tennis" },
  { player: "Novak Djokovic", quote: "The mind is the strongest muscle. Train it daily.", category: "tennis" },
  { player: "Michael Jordan", quote: "I've missed more than 9000 shots. I've failed over and over. That's why I succeed.", category: "basketball" },
  { player: "Kobe Bryant", quote: "Everything negative is an opportunity. Pressure is a privilege.", category: "basketball" },
  { player: "LeBron James", quote: "I like criticism. It makes me strong.", category: "basketball" },
  { player: "Stephen Curry", quote: "Success is not an accident. It's preparation meeting opportunity.", category: "basketball" },
  { player: "Usain Bolt", quote: "Dreams don't work unless you do. Speed is my language.", category: "athletics" },
  { player: "Simone Biles", quote: "I'm not the next Usain Bolt or Michael Phelps. I'm the first Simone Biles.", category: "gymnastics" },
  { player: "Muhammad Ali", quote: "Float like a butterfly, sting like a bee. Impossible is nothing.", category: "boxing" },
  { player: "Mike Tyson", quote: "Everyone has a plan until they get punched in the mouth.", category: "boxing" },
  { player: "Floyd Mayweather", quote: "Hard work, dedication, and sacrifice. That's the formula.", category: "boxing" },
  
  // ðŸ† COACHES & MANAGERS
  { player: "Sir Alex Ferguson", quote: "Attack wins you games. Defense wins you titles.", category: "coach" },
  { player: "Pep Guardiola", quote: "The ball is faster than any player. Keep it moving.", category: "coach" },
  { player: "JÃ¼rgen Klopp", quote: "We don't go from zero to hero. We go from good to better to best.", category: "coach" },
  { player: "Carlo Ancelotti", quote: "Calmness is the key to victory. Panic is the enemy.", category: "coach" },
  { player: "ArsÃ¨ne Wenger", quote: "Football is about enjoyment and passion. Never lose that.", category: "coach" },
  { player: "JosÃ© Mourinho", quote: "I don't chase success. Success chases me because I'm prepared.", category: "coach" },
  { player: "Diego Simeone", quote: "Passion without tactics is chaos. Tactics without passion is boring.", category: "coach" },
  
  // ðŸ’¼ ENTREPRENEURS & LEADERS
  { player: "Elon Musk", quote: "When something is important enough, you do it even if the odds are not in your favor.", category: "business" },
  { player: "Steve Jobs", quote: "The only way to do great work is to love what you do.", category: "business" },
  { player: "Oprah Winfrey", quote: "Turn your wounds into wisdom. Your story is your power.", category: "business" },
  { player: "Jeff Bezos", quote: "I knew that if I failed, I wouldn't regret that. But I knew I'd regret not trying.", category: "business" },
  { player: "Richard Branson", quote: "Screw it, let's do it! Boldness is the key to success.", category: "business" },
  { player: "Warren Buffett", quote: "Someone's sitting in the shade today because someone planted a tree long ago.", category: "business" },
  { player: "Bill Gates", quote: "Your most unhappy customers are your greatest source of learning.", category: "business" },
  
  // ðŸŽ­ ENTERTAINERS & ARTISTS
  { player: "Dwayne Johnson", quote: "Success isn't always about greatness. It's about consistency.", category: "entertainment" },
  { player: "Will Smith", quote: "The first step is you have to say that you can.", category: "entertainment" },
  { player: "Jim Carrey", quote: "Behind every great man is a woman rolling her eyes.", category: "entertainment" },
  { player: "BeyoncÃ©", quote: "Power is not given to you. You have to take it.", category: "entertainment" },
  { player: "Jay-Z", quote: "I'm not a businessman. I'm a business, man!", category: "entertainment" },
  
  // ðŸ§  PHILOSOPHERS & THINKERS
  { player: "Nelson Mandela", quote: "It always seems impossible until it's done.", category: "leadership" },
  { player: "Martin Luther King Jr.", quote: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", category: "leadership" },
  { player: "Maya Angelou", quote: "You may encounter many defeats, but you must not be defeated.", category: "leadership" },
  { player: "Winston Churchill", quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", category: "leadership" },
  { player: "Theodore Roosevelt", quote: "Believe you can and you're halfway there.", category: "leadership" },
  { player: "Confucius", quote: "It does not matter how slowly you go as long as you do not stop.", category: "wisdom" },
  { player: "Aristotle", quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", category: "wisdom" },
  { player: "Socrates", quote: "The only true wisdom is in knowing you know nothing.", category: "wisdom" },
  
  // ðŸš€ MODERN INFLUENCERS
  { player: "Gary Vaynerchuk", quote: "Stop complaining. Start executing. The market doesn't care about your feelings.", category: "business" },
  { player: "Tim Ferriss", quote: "Focus on being productive instead of busy.", category: "productivity" },
  { player: "Tony Robbins", quote: "Setting goals is the first step in turning the invisible into the visible.", category: "motivation" },
];

// ðŸŒ TRANSLATIONS (Major Languages)
export const TRANSLATIONS = {
  en: {
    addQuote: "Add Your Quote",
    yourName: "Your Name",
    yourQuote: "Your Inspirational Quote",
    submit: "Submit Quote",
    cancel: "Cancel",
    language: "Language",
    selectLanguage: "Select Language",
    category: "Category",
    filterByCategory: "Filter by Category",
    all: "All",
    football: "âš½ Football",
    basketball: "ðŸ€ Basketball",
    tennis: "ðŸŽ¾ Tennis",
    boxing: "ðŸ¥Š Boxing",
    athletics: "ðŸƒ Athletics",
    gymnastics: "ðŸ¤¸ Gymnastics",
    coach: "ðŸ‘” Coach",
    business: "ðŸ’¼ Business",
    entertainment: "ðŸŽ¬ Entertainment",
    leadership: "ðŸ‘‘ Leadership",
    wisdom: "ðŸ“š Wisdom",
    motivation: "ðŸ”¥ Motivation",
    productivity: "âš¡ Productivity",
    customQuotes: "ðŸ“ Your Quotes",
    noCustomQuotes: "No custom quotes yet. Be the first to inspire!",
    profanityError: "Please remove inappropriate language",
    emptyFieldsError: "Please fill in all fields",
    successMessage: "Quote added successfully!",
    refreshQuotes: "ðŸ” More Inspiration",
    dailyWisdom: "ðŸŒŸ Daily Football Wisdom",
    inspirationFrom: "Inspiration from the world's best",
    whileWeLoad: "âœ¨ While We Load...",
    freshMotivation: "ðŸ’­ Fresh Motivation",
    selectPlayer: "Select a player:",
    unnamed: "Unnamed",
    noTipsYet: "No personalized tips yet.",
    createProfile: "Create a player profile to get AI-powered coaching!",
    createPlayer: "âž• Create Player",
    consultingAI: "Consulting the AI Coach...",
    errorTitle: "âš ï¸ Oops!",
    tryAgain: "ðŸ”„ Try Again",
    back: "â† Back"
  },
  es: {
    addQuote: "Agregar Tu Cita",
    yourName: "Tu Nombre",
    yourQuote: "Tu Cita Inspiradora",
    submit: "Enviar Cita",
    cancel: "Cancelar",
    language: "Idioma",
    selectLanguage: "Seleccionar Idioma",
    category: "CategorÃ­a",
    filterByCategory: "Filtrar por CategorÃ­a",
    all: "Todas",
    football: "âš½ FÃºtbol",
    basketball: "ðŸ€ Baloncesto",
    tennis: "ðŸŽ¾ Tenis",
    boxing: "ðŸ¥Š Boxeo",
    athletics: "ðŸƒ Atletismo",
    gymnastics: "ðŸ¤¸ Gimnasia",
    coach: "ðŸ‘” Entrenador",
    business: "ðŸ’¼ Negocios",
    entertainment: "ðŸŽ¬ Entretenimiento",
    leadership: "ðŸ‘‘ Liderazgo",
    wisdom: "ðŸ“š SabidurÃ­a",
    motivation: "ðŸ”¥ MotivaciÃ³n",
    productivity: "âš¡ Productividad",
    customQuotes: "ðŸ“ Tus Citas",
    noCustomQuotes: "AÃºn no hay citas personalizadas. Â¡SÃ© el primero en inspirar!",
    profanityError: "Por favor elimina lenguaje inapropiado",
    emptyFieldsError: "Por favor completa todos los campos",
    successMessage: "Â¡Cita agregada exitosamente!",
    refreshQuotes: "ðŸ” MÃ¡s InspiraciÃ³n",
    dailyWisdom: "ðŸŒŸ SabidurÃ­a Diaria del FÃºtbol",
    inspirationFrom: "InspiraciÃ³n de los mejores del mundo",
    whileWeLoad: "âœ¨ Mientras Cargamos...",
    freshMotivation: "ðŸ’­ MotivaciÃ³n Fresca",
    selectPlayer: "Selecciona un jugador:",
    unnamed: "Sin Nombre",
    noTipsYet: "AÃºn no hay consejos personalizados.",
    createProfile: "Â¡Crea un perfil de jugador para obtener coaching con IA!",
    createPlayer: "âž• Crear Jugador",
    consultingAI: "Consultando al Entrenador IA...",
    errorTitle: "âš ï¸ Â¡Ups!",
    tryAgain: "ðŸ”„ Intentar de Nuevo",
    back: "â† AtrÃ¡s"
  },
  fr: {
    addQuote: "Ajouter Votre Citation",
    yourName: "Votre Nom",
    yourQuote: "Votre Citation Inspirante",
    submit: "Soumettre",
    cancel: "Annuler",
    language: "Langue",
    selectLanguage: "Choisir la Langue",
    category: "CatÃ©gorie",
    filterByCategory: "Filtrer par CatÃ©gorie",
    all: "Toutes",
    football: "âš½ Football",
    basketball: "ðŸ€ Basket-ball",
    tennis: "ðŸŽ¾ Tennis",
    boxing: "ðŸ¥Š Boxe",
    athletics: "ðŸƒ AthlÃ©tisme",
    gymnastics: "ðŸ¤¸ Gymnastique",
    coach: "ðŸ‘” EntraÃ®neur",
    business: "ðŸ’¼ Affaires",
    entertainment: "ðŸŽ¬ Divertissement",
    leadership: "ðŸ‘‘ Leadership",
    wisdom: "ðŸ“š Sagesse",
    motivation: "ðŸ”¥ Motivation",
    productivity: "âš¡ ProductivitÃ©",
    customQuotes: "ðŸ“ Vos Citations",
    noCustomQuotes: "Pas encore de citations personnalisÃ©es. Soyez le premier Ã  inspirer!",
    profanityError: "Veuillez supprimer le langage inappropriÃ©",
    emptyFieldsError: "Veuillez remplir tous les champs",
    successMessage: "Citation ajoutÃ©e avec succÃ¨s!",
    refreshQuotes: "ðŸ” Plus d'Inspiration",
    dailyWisdom: "ðŸŒŸ Sagesse Quotidienne du Football",
    inspirationFrom: "Inspiration des meilleurs au monde",
    whileWeLoad: "âœ¨ Pendant le Chargement...",
    freshMotivation: "ðŸ’­ Motivation FraÃ®che",
    selectPlayer: "SÃ©lectionnez un joueur:",
    unnamed: "Sans Nom",
    noTipsYet: "Pas encore de conseils personnalisÃ©s.",
    createProfile: "CrÃ©ez un profil de joueur pour obtenir un coaching IA!",
    createPlayer: "âž• CrÃ©er Joueur",
    consultingAI: "Consultation de l'IA Coach...",
    errorTitle: "âš ï¸ Oups!",
    tryAgain: "ðŸ”„ RÃ©essayer",
    back: "â† Retour"
  },
  pt: {
    addQuote: "Adicionar Sua CitaÃ§Ã£o",
    yourName: "Seu Nome",
    yourQuote: "Sua CitaÃ§Ã£o Inspiradora",
    submit: "Enviar",
    cancel: "Cancelar",
    language: "Idioma",
    selectLanguage: "Selecionar Idioma",
    category: "Categoria",
    filterByCategory: "Filtrar por Categoria",
    all: "Todas",
    football: "âš½ Futebol",
    basketball: "ðŸ€ Basquete",
    tennis: "ðŸŽ¾ TÃªnis",
    boxing: "ðŸ¥Š Boxe",
    athletics: "ðŸƒ Atletismo",
    gymnastics: "ðŸ¤¸ GinÃ¡stica",
    coach: "ðŸ‘” Treinador",
    business: "ðŸ’¼ NegÃ³cios",
    entertainment: "ðŸŽ¬ Entretenimento",
    leadership: "ðŸ‘‘ LideranÃ§a",
    wisdom: "ðŸ“š Sabedoria",
    motivation: "ðŸ”¥ MotivaÃ§Ã£o",
    productivity: "âš¡ Produtividade",
    customQuotes: "ðŸ“ Suas CitaÃ§Ãµes",
    noCustomQuotes: "Ainda nÃ£o hÃ¡ citaÃ§Ãµes personalizadas. Seja o primeiro a inspirar!",
    profanityError: "Por favor remova linguagem inadequada",
    emptyFieldsError: "Por favor preencha todos os campos",
    successMessage: "CitaÃ§Ã£o adicionada com sucesso!",
    refreshQuotes: "ðŸ” Mais InspiraÃ§Ã£o",
    dailyWisdom: "ðŸŒŸ Sabedoria DiÃ¡ria do Futebol",
    inspirationFrom: "InspiraÃ§Ã£o dos melhores do mundo",
    whileWeLoad: "âœ¨ Enquanto Carregamos...",
    freshMotivation: "ðŸ’­ MotivaÃ§Ã£o Fresca",
    selectPlayer: "Selecione um jogador:",
    unnamed: "Sem Nome",
    noTipsYet: "Ainda nÃ£o hÃ¡ dicas personalizadas.",
    createProfile: "Crie um perfil de jogador para obter coaching com IA!",
    createPlayer: "âž• Criar Jogador",
    consultingAI: "Consultando o Treinador IA...",
    errorTitle: "âš ï¸ Ops!",
    tryAgain: "ðŸ”„ Tentar Novamente",
    back: "â† Voltar"
  },
  ar: {
    addQuote: "Ø£Ø¶Ù Ø§Ù‚ØªØ¨Ø§Ø³Ùƒ",
    yourName: "Ø§Ø³Ù…Ùƒ",
    yourQuote: "Ø§Ù‚ØªØ¨Ø§Ø³Ùƒ Ø§Ù„Ù…Ù„Ù‡Ù…",
    submit: "Ø¥Ø±Ø³Ø§Ù„",
    cancel: "Ø¥Ù„ØºØ§Ø¡",
    language: "Ø§Ù„Ù„ØºØ©",
    selectLanguage: "Ø§Ø®ØªØ± Ø§Ù„Ù„ØºØ©",
    category: "Ø§Ù„ÙØ¦Ø©",
    filterByCategory: "ØªØµÙÙŠØ© Ø­Ø³Ø¨ Ø§Ù„ÙØ¦Ø©",
    all: "Ø§Ù„ÙƒÙ„",
    football: "âš½ ÙƒØ±Ø© Ø§Ù„Ù‚Ø¯Ù…",
    basketball: "ðŸ€ ÙƒØ±Ø© Ø§Ù„Ø³Ù„Ø©",
    tennis: "ðŸŽ¾ Ø§Ù„ØªÙ†Ø³",
    boxing: "ðŸ¥Š Ø§Ù„Ù…Ù„Ø§ÙƒÙ…Ø©",
    athletics: "ðŸƒ Ø£Ù„Ø¹Ø§Ø¨ Ø§Ù„Ù‚ÙˆÙ‰",
    gymnastics: "ðŸ¤¸ Ø§Ù„Ø¬Ù…Ø¨Ø§Ø²",
    coach: "ðŸ‘” Ù…Ø¯Ø±Ø¨",
    business: "ðŸ’¼ Ø£Ø¹Ù…Ø§Ù„",
    entertainment: "ðŸŽ¬ ØªØ±ÙÙŠÙ‡",
    leadership: "ðŸ‘‘ Ù‚ÙŠØ§Ø¯Ø©",
    wisdom: "ðŸ“š Ø­ÙƒÙ…Ø©",
    motivation: "ðŸ”¥ ØªØ­ÙÙŠØ²",
    productivity: "âš¡ Ø¥Ù†ØªØ§Ø¬ÙŠØ©",
    customQuotes: "ðŸ“ Ø§Ù‚ØªØ¨Ø§Ø³Ø§ØªÙƒ",
    noCustomQuotes: "Ù„Ø§ ØªÙˆØ¬Ø¯ Ø§Ù‚ØªØ¨Ø§Ø³Ø§Øª Ù…Ø®ØµØµØ© Ø¨Ø¹Ø¯. ÙƒÙ† Ø§Ù„Ø£ÙˆÙ„ ÙÙŠ Ø§Ù„Ø¥Ù„Ù‡Ø§Ù…!",
    profanityError: "ÙŠØ±Ø¬Ù‰ Ø¥Ø²Ø§Ù„Ø© Ø§Ù„Ù„ØºØ© ØºÙŠØ± Ø§Ù„Ù„Ø§Ø¦Ù‚Ø©",
    emptyFieldsError: "ÙŠØ±Ø¬Ù‰ Ù…Ù„Ø¡ Ø¬Ù…ÙŠØ¹ Ø§Ù„Ø­Ù‚ÙˆÙ„",
    successMessage: "ØªÙ…Øª Ø¥Ø¶Ø§ÙØ© Ø§Ù„Ø§Ù‚ØªØ¨Ø§Ø³ Ø¨Ù†Ø¬Ø§Ø­!",
    refreshQuotes: "ðŸ” Ø§Ù„Ù…Ø²ÙŠØ¯ Ù…Ù† Ø§Ù„Ø¥Ù„Ù‡Ø§Ù…",
    dailyWisdom: "ðŸŒŸ Ø­ÙƒÙ…Ø© ÙƒØ±Ø© Ø§Ù„Ù‚Ø¯Ù… Ø§Ù„ÙŠÙˆÙ…ÙŠØ©",
    inspirationFrom: "Ø¥Ù„Ù‡Ø§Ù… Ù…Ù† Ø§Ù„Ø£ÙØ¶Ù„ ÙÙŠ Ø§Ù„Ø¹Ø§Ù„Ù…",
    whileWeLoad: "âœ¨ Ø¨ÙŠÙ†Ù…Ø§ Ù†Ø­Ù…Ù‘Ù„...",
    freshMotivation: "ðŸ’­ ØªØ­ÙÙŠØ² Ø¬Ø¯ÙŠØ¯",
    selectPlayer: "Ø§Ø®ØªØ± Ù„Ø§Ø¹Ø¨Ø§Ù‹:",
    unnamed: "Ø¨Ø¯ÙˆÙ† Ø§Ø³Ù…",
    noTipsYet: "Ù„Ø§ ØªÙˆØ¬Ø¯ Ù†ØµØ§Ø¦Ø­ Ù…Ø®ØµØµØ© Ø¨Ø¹Ø¯.",
    createProfile: "Ø£Ù†Ø´Ø¦ Ù…Ù„Ù Ù„Ø§Ø¹Ø¨ Ù„Ù„Ø­ØµÙˆÙ„ Ø¹Ù„Ù‰ ØªØ¯Ø±ÙŠØ¨ Ø¨Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ!",
    createPlayer: "âž• Ø¥Ù†Ø´Ø§Ø¡ Ù„Ø§Ø¹Ø¨",
    consultingAI: "Ø§Ø³ØªØ´Ø§Ø±Ø© Ø§Ù„Ù…Ø¯Ø±Ø¨ Ø§Ù„Ø°ÙƒÙŠ...",
    errorTitle: "âš ï¸ Ø¹Ø°Ø±Ø§Ù‹!",
    tryAgain: "ðŸ”„ Ø­Ø§ÙˆÙ„ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰",
    back: "â† Ø±Ø¬ÙˆØ¹"
  },
  zh: {
    addQuote: "æ·»åŠ æ‚¨çš„åè¨€",
    yourName: "æ‚¨çš„åå­—",
    yourQuote: "æ‚¨çš„åŠ±å¿—åè¨€",
    submit: "æäº¤",
    cancel: "å–æ¶ˆ",
    language: "è¯­è¨€",
    selectLanguage: "é€‰æ‹©è¯­è¨€",
    category: "ç±»åˆ«",
    filterByCategory: "æŒ‰ç±»åˆ«ç­›é€‰",
    all: "å…¨éƒ¨",
    football: "âš½ è¶³çƒ",
    basketball: "ðŸ€ ç¯®çƒ",
    tennis: "ðŸŽ¾ ç½‘çƒ",
    boxing: "ðŸ¥Š æ‹³å‡»",
    athletics: "ðŸƒ ç”°å¾„",
    gymnastics: "ðŸ¤¸ ä½“æ“",
    coach: "ðŸ‘” æ•™ç»ƒ",
    business: "ðŸ’¼ å•†ä¸š",
    entertainment: "ðŸŽ¬ å¨±ä¹",
    leadership: "ðŸ‘‘ é¢†å¯¼åŠ›",
    wisdom: "ðŸ“š æ™ºæ…§",
    motivation: "ðŸ”¥ æ¿€åŠ±",
    productivity: "âš¡ ç”Ÿäº§åŠ›",
    customQuotes: "ðŸ“ æ‚¨çš„åè¨€",
    noCustomQuotes: "è¿˜æ²¡æœ‰è‡ªå®šä¹‰åè¨€ã€‚æˆä¸ºç¬¬ä¸€ä¸ªæ¿€åŠ±ä»–äººçš„äººï¼",
    profanityError: "è¯·åˆ é™¤ä¸å½“è¯­è¨€",
    emptyFieldsError: "è¯·å¡«å†™æ‰€æœ‰å­—æ®µ",
    successMessage: "åè¨€æ·»åŠ æˆåŠŸï¼",
    refreshQuotes: "ðŸ” æ›´å¤šçµæ„Ÿ",
    dailyWisdom: "ðŸŒŸ æ¯æ—¥è¶³çƒæ™ºæ…§",
    inspirationFrom: "æ¥è‡ªä¸–ç•Œæœ€ä½³çš„çµæ„Ÿ",
    whileWeLoad: "âœ¨ åŠ è½½ä¸­...",
    freshMotivation: "ðŸ’­ æ–°é²œæ¿€åŠ±",
    selectPlayer: "é€‰æ‹©çƒå‘˜:",
    unnamed: "æœªå‘½å",
    noTipsYet: "è¿˜æ²¡æœ‰ä¸ªæ€§åŒ–å»ºè®®ã€‚",
    createProfile: "åˆ›å»ºçƒå‘˜æ¡£æ¡ˆä»¥èŽ·å–AIæ•™ç»ƒæŒ‡å¯¼ï¼",
    createPlayer: "âž• åˆ›å»ºçƒå‘˜",
    consultingAI: "å’¨è¯¢AIæ•™ç»ƒ...",
    errorTitle: "âš ï¸ å“Žå‘€!",
    tryAgain: "ðŸ”„ é‡è¯•",
    back: "â† è¿”å›ž"
  },
  de: {
    addQuote: "Zitat HinzufÃ¼gen",
    yourName: "Ihr Name",
    yourQuote: "Ihr Inspirierendes Zitat",
    submit: "Einreichen",
    cancel: "Abbrechen",
    language: "Sprache",
    selectLanguage: "Sprache AuswÃ¤hlen",
    category: "Kategorie",
    filterByCategory: "Nach Kategorie Filtern",
    all: "Alle",
    football: "âš½ FuÃŸball",
    basketball: "ðŸ€ Basketball",
    tennis: "ðŸŽ¾ Tennis",
    boxing: "ðŸ¥Š Boxen",
    athletics: "ðŸƒ Leichtathletik",
    gymnastics: "ðŸ¤¸ Gymnastik",
    coach: "ðŸ‘” Trainer",
    business: "ðŸ’¼ GeschÃ¤ft",
    entertainment: "ðŸŽ¬ Unterhaltung",
    leadership: "ðŸ‘‘ FÃ¼hrung",
    wisdom: "ðŸ“š Weisheit",
    motivation: "ðŸ”¥ Motivation",
    productivity: "âš¡ ProduktivitÃ¤t",
    customQuotes: "ðŸ“ Ihre Zitate",
    noCustomQuotes: "Noch keine benutzerdefinierten Zitate. Seien Sie der Erste, der inspiriert!",
    profanityError: "Bitte entfernen Sie unangemessene Sprache",
    emptyFieldsError: "Bitte fÃ¼llen Sie alle Felder aus",
    successMessage: "Zitat erfolgreich hinzugefÃ¼gt!",
    refreshQuotes: "ðŸ” Mehr Inspiration",
    dailyWisdom: "ðŸŒŸ TÃ¤gliche FuÃŸball-Weisheit",
    inspirationFrom: "Inspiration von den Besten der Welt",
    whileWeLoad: "âœ¨ WÃ¤hrend des Ladens...",
    freshMotivation: "ðŸ’­ Frische Motivation",
    selectPlayer: "Spieler auswÃ¤hlen:",
    unnamed: "Unbenannt",
    noTipsYet: "Noch keine personalisierten Tipps.",
    createProfile: "Erstellen Sie ein Spielerprofil fÃ¼r AI-Coaching!",
    createPlayer: "âž• Spieler Erstellen",
    consultingAI: "AI-Trainer wird konsultiert...",
    errorTitle: "âš ï¸ Hoppla!",
    tryAgain: "ðŸ”„ Erneut Versuchen",
    back: "â† ZurÃ¼ck"
  },
  it: {
    addQuote: "Aggiungi la Tua Citazione",
    yourName: "Il Tuo Nome",
    yourQuote: "La Tua Citazione Ispiratrice",
    submit: "Invia",
    cancel: "Annulla",
    language: "Lingua",
    selectLanguage: "Seleziona Lingua",
    category: "Categoria",
    filterByCategory: "Filtra per Categoria",
    all: "Tutte",
    football: "âš½ Calcio",
    basketball: "ðŸ€ Pallacanestro",
    tennis: "ðŸŽ¾ Tennis",
    boxing: "ðŸ¥Š Pugilato",
    athletics: "ðŸƒ Atletica",
    gymnastics: "ðŸ¤¸ Ginnastica",
    coach: "ðŸ‘” Allenatore",
    business: "ðŸ’¼ Affari",
    entertainment: "ðŸŽ¬ Intrattenimento",
    leadership: "ðŸ‘‘ Leadership",
    wisdom: "ðŸ“š Saggezza",
    motivation: "ðŸ”¥ Motivazione",
    productivity: "âš¡ ProduttivitÃ ",
    customQuotes: "ðŸ“ Le Tue Citazioni",
    noCustomQuotes: "Nessuna citazione personalizzata ancora. Sii il primo a ispirare!",
    profanityError: "Si prega di rimuovere il linguaggio inappropriato",
    emptyFieldsError: "Si prega di compilare tutti i campi",
    successMessage: "Citazione aggiunta con successo!",
    refreshQuotes: "ðŸ” Altra Ispirazione",
    dailyWisdom: "ðŸŒŸ Saggezza Quotidiana del Calcio",
    inspirationFrom: "Ispirazione dai migliori al mondo",
    whileWeLoad: "âœ¨ Durante il Caricamento...",
    freshMotivation: "ðŸ’­ Motivazione Fresca",
    selectPlayer: "Seleziona un giocatore:",
    unnamed: "Senza Nome",
    noTipsYet: "Nessun consiglio personalizzato ancora.",
    createProfile: "Crea un profilo giocatore per ottenere coaching AI!",
    createPlayer: "âž• Crea Giocatore",
    consultingAI: "Consultando l'AI Coach...",
    errorTitle: "âš ï¸ Ops!",
    tryAgain: "ðŸ”„ Riprova",
    back: "â† Indietro"
  }
};

// ðŸš« PROFANITY FILTER (Simple word list)
export const PROFANE_WORDS = [
  'damn', 'shit', 'fuck', 'bitch', 'ass', 'hell', 'crap', 'stupid', 'idiot', 'dumb',
  'bastard', 'piss', 'suck', 'damn', 'goddamn', 'fucking', 'bullshit', 'asshole'
];

export const containsProfanity = (text) => {
  const lowerText = text.toLowerCase();
  return PROFANE_WORDS.some(word => lowerText.includes(word));
};

// ðŸŒ SIMPLE TRANSLATOR (Dictionary-based for common phrases)
export const translateQuote = (quote, targetLang) => {
  if (targetLang === 'en') return quote;
  
  // Simple word replacement for demo (in production, use Google Translate API)
  const translations = {
    'en': { 'dream': 'dream', 'work': 'work', 'success': 'success', 'hard': 'hard' },
    'es': { 'dream': 'sueÃ±o', 'work': 'trabajo', 'success': 'Ã©xito', 'hard': 'duro' },
    'fr': { 'dream': 'rÃªve', 'work': 'travail', 'success': 'succÃ¨s', 'hard': 'dur' },
    'pt': { 'dream': 'sonho', 'work': 'trabalho', 'success': 'sucesso', 'hard': 'difÃ­cil' },
    // Add more as needed
  };
  
  let translated = quote;
  const dict = translations[targetLang] || translations['en'];
  
  Object.keys(dict).forEach(word => {
    const regex = new RegExp(`\\b${word}\\b`, 'gi');
    translated = translated.replace(regex, dict[word]);
  });
  
  return translated;
};

export default {
  MOTIVATIONAL_QUOTES,
  TRANSLATIONS,
  containsProfanity,
  translateQuote
};