// app/utils/quotesDatabase.js

export const MOTIVATIONAL_QUOTES = [
  // ⚽ FOOTBALLERS
  { player: "Cristiano Ronaldo", quote: "Your love makes me strong, your hate makes me unstoppable.", category: "football" },
  { player: "Lionel Messi", quote: "You have to fight to reach your dream. You have to sacrifice and work hard for it.", category: "football" },
  { player: "Mohamed Salah", quote: "I'm not here to talk about the past. I'm here to win.", category: "football" },
  { player: "Virgil van Dijk", quote: "Confidence comes from preparation. Train like you play.", category: "football" },
  { player: "Sam Kerr", quote: "Believe in yourself even when no one else does. That's when magic happens.", category: "football" },
  { player: "Kylian Mbappé", quote: "Speed is nothing without direction. Know your goal.", category: "football" },
  { player: "Megan Rapinoe", quote: "Be louder than your fear. The pitch is your stage.", category: "football" },
  { player: "Erling Haaland", quote: "Goals don't come from wishing. They come from working.", category: "football" },
  { player: "Alex Morgan", quote: "Success is earned, not given. Every day is a chance to improve.", category: "football" },
  { player: "Neymar Jr", quote: "Creativity is the weapon. Technique is the ammunition.", category: "football" },
  { player: "Lucy Bronze", quote: "Hard work beats talent when talent doesn't work hard.", category: "football" },
  { player: "Ronaldinho", quote: "Enjoy the game. Smile, have fun, and let your feet do the talking.", category: "football" },
  { player: "Marta", quote: "I play for the girls who dream big. Never give up on your dreams.", category: "football" },
  { player: "Zinedine Zidane", quote: "Elegance is not about showing off. It's about making it look easy.", category: "football" },
  { player: "Abby Wambach", quote: "Failure is fuel. Use it to burn brighter.", category: "football" },
  { player: "Thierry Henry", quote: "The ball is round, but the game is square. Anything can happen.", category: "football" },
  { player: "Ada Hegerberg", quote: "I don't play to be second. I play to win everything.", category: "football" },
  { player: "Andrés Iniesta", quote: "The best pass is the one before the goal. Patience wins games.", category: "football" },
  { player: "Serena Williams", quote: "I'm not afraid of failure. I'm afraid of not trying.", category: "tennis" },
  { player: "Roger Federer", quote: "Doubt kills more dreams than failure ever will.", category: "tennis" },
  { player: "Rafael Nadal", quote: "Every point is a battle. Every match is a war.", category: "tennis" },
  { player: "Novak Djokovic", quote: "The mind is the strongest muscle. Train it daily.", category: "tennis" },
  { player: "Michael Jordan", quote: "I've missed more than 9000 shots. I've failed over and over. That's why I succeed.", category: "basketball" },
  { player: "Kobe Bryant", quote: "Everything negative is an opportunity. Pressure is a privilege.", category: "basketball" },
  { player: "LeBron James", quote: "I like criticism. It makes me strong.", category: "basketball" },
  { player: "Stephen Curry", quote: "Success is not an accident. It's preparation meeting opportunity.", category: "basketball" },
  { player: "Usain Bolt", quote: "Dreams don't work unless you do. Speed is my language.", category: "athletics" },
  { player: "Simone Biles", quote: "I'm not the next Usain Bolt or Michael Phelps. I'm the first Simone Biles.", category: "gymnastics" },
  { player: "Muhammad Ali", quote: "Float like a butterfly, sting like a bee. Impossible is nothing.", category: "boxing" },
  { player: "Mike Tyson", quote: "Everyone has a plan until they get punched in the mouth.", category: "boxing" },
  { player: "Floyd Mayweather", quote: "Hard work, dedication, and sacrifice. That's the formula.", category: "boxing" },
  
  // 🏆 COACHES & MANAGERS
  { player: "Sir Alex Ferguson", quote: "Attack wins you games. Defense wins you titles.", category: "coach" },
  { player: "Pep Guardiola", quote: "The ball is faster than any player. Keep it moving.", category: "coach" },
  { player: "Jürgen Klopp", quote: "We don't go from zero to hero. We go from good to better to best.", category: "coach" },
  { player: "Carlo Ancelotti", quote: "Calmness is the key to victory. Panic is the enemy.", category: "coach" },
  { player: "Arsène Wenger", quote: "Football is about enjoyment and passion. Never lose that.", category: "coach" },
  { player: "José Mourinho", quote: "I don't chase success. Success chases me because I'm prepared.", category: "coach" },
  { player: "Diego Simeone", quote: "Passion without tactics is chaos. Tactics without passion is boring.", category: "coach" },
  
  // 💼 ENTREPRENEURS & LEADERS
  { player: "Elon Musk", quote: "When something is important enough, you do it even if the odds are not in your favor.", category: "business" },
  { player: "Steve Jobs", quote: "The only way to do great work is to love what you do.", category: "business" },
  { player: "Oprah Winfrey", quote: "Turn your wounds into wisdom. Your story is your power.", category: "business" },
  { player: "Jeff Bezos", quote: "I knew that if I failed, I wouldn't regret that. But I knew I'd regret not trying.", category: "business" },
  { player: "Richard Branson", quote: "Screw it, let's do it! Boldness is the key to success.", category: "business" },
  { player: "Warren Buffett", quote: "Someone's sitting in the shade today because someone planted a tree long ago.", category: "business" },
  { player: "Bill Gates", quote: "Your most unhappy customers are your greatest source of learning.", category: "business" },
  
  // 🎭 ENTERTAINERS & ARTISTS
  { player: "Dwayne Johnson", quote: "Success isn't always about greatness. It's about consistency.", category: "entertainment" },
  { player: "Will Smith", quote: "The first step is you have to say that you can.", category: "entertainment" },
  { player: "Jim Carrey", quote: "Behind every great man is a woman rolling her eyes.", category: "entertainment" },
  { player: "Beyoncé", quote: "Power is not given to you. You have to take it.", category: "entertainment" },
  { player: "Jay-Z", quote: "I'm not a businessman. I'm a business, man!", category: "entertainment" },
  
  // 🧠 PHILOSOPHERS & THINKERS
  { player: "Nelson Mandela", quote: "It always seems impossible until it's done.", category: "leadership" },
  { player: "Martin Luther King Jr.", quote: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", category: "leadership" },
  { player: "Maya Angelou", quote: "You may encounter many defeats, but you must not be defeated.", category: "leadership" },
  { player: "Winston Churchill", quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", category: "leadership" },
  { player: "Theodore Roosevelt", quote: "Believe you can and you're halfway there.", category: "leadership" },
  { player: "Confucius", quote: "It does not matter how slowly you go as long as you do not stop.", category: "wisdom" },
  { player: "Aristotle", quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", category: "wisdom" },
  { player: "Socrates", quote: "The only true wisdom is in knowing you know nothing.", category: "wisdom" },
  
  // 🚀 MODERN INFLUENCERS
  { player: "Gary Vaynerchuk", quote: "Stop complaining. Start executing. The market doesn't care about your feelings.", category: "business" },
  { player: "Tim Ferriss", quote: "Focus on being productive instead of busy.", category: "productivity" },
  { player: "Tony Robbins", quote: "Setting goals is the first step in turning the invisible into the visible.", category: "motivation" },
];

// 🌍 TRANSLATIONS (Major Languages)
export const TRANSLATIONS = {
  en: {
    addQuote: "Add Your Quote",
    yourName: "Your Name",
    yourQuote: "Your Inspirational Quote",
    submit: "Submit Quote",
    cancel: "Cancel",
    language: "Language",
    selectLanguage: "Select Language",
    category: "Category",
    filterByCategory: "Filter by Category",
    all: "All",
    football: "⚽ Football",
    basketball: "🏀 Basketball",
    tennis: "🎾 Tennis",
    boxing: "🥊 Boxing",
    athletics: "🏃 Athletics",
    gymnastics: "🤸 Gymnastics",
    coach: "👔 Coach",
    business: "💼 Business",
    entertainment: "🎬 Entertainment",
    leadership: "👑 Leadership",
    wisdom: "📚 Wisdom",
    motivation: "🔥 Motivation",
    productivity: "⚡ Productivity",
    customQuotes: "📝 Your Quotes",
    noCustomQuotes: "No custom quotes yet. Be the first to inspire!",
    profanityError: "Please remove inappropriate language",
    emptyFieldsError: "Please fill in all fields",
    successMessage: "Quote added successfully!",
    refreshQuotes: "🔁 More Inspiration",
    dailyWisdom: "🌟 Daily Football Wisdom",
    inspirationFrom: "Inspiration from the world's best",
    whileWeLoad: "✨ While We Load...",
    freshMotivation: "💭 Fresh Motivation",
    selectPlayer: "Select a player:",
    unnamed: "Unnamed",
    noTipsYet: "No personalized tips yet.",
    createProfile: "Create a player profile to get AI-powered coaching!",
    createPlayer: "➕ Create Player",
    consultingAI: "Consulting the AI Coach...",
    errorTitle: "⚠️ Oops!",
    tryAgain: "🔄 Try Again",
    back: "← Back"
  },
  es: {
    addQuote: "Agregar Tu Cita",
    yourName: "Tu Nombre",
    yourQuote: "Tu Cita Inspiradora",
    submit: "Enviar Cita",
    cancel: "Cancelar",
    language: "Idioma",
    selectLanguage: "Seleccionar Idioma",
    category: "Categoría",
    filterByCategory: "Filtrar por Categoría",
    all: "Todas",
    football: "⚽ Fútbol",
    basketball: "🏀 Baloncesto",
    tennis: "🎾 Tenis",
    boxing: "🥊 Boxeo",
    athletics: "🏃 Atletismo",
    gymnastics: "🤸 Gimnasia",
    coach: "👔 Entrenador",
    business: "💼 Negocios",
    entertainment: "🎬 Entretenimiento",
    leadership: "👑 Liderazgo",
    wisdom: "📚 Sabiduría",
    motivation: "🔥 Motivación",
    productivity: "⚡ Productividad",
    customQuotes: "📝 Tus Citas",
    noCustomQuotes: "Aún no hay citas personalizadas. ¡Sé el primero en inspirar!",
    profanityError: "Por favor elimina lenguaje inapropiado",
    emptyFieldsError: "Por favor completa todos los campos",
    successMessage: "¡Cita agregada exitosamente!",
    refreshQuotes: "🔁 Más Inspiración",
    dailyWisdom: "🌟 Sabiduría Diaria del Fútbol",
    inspirationFrom: "Inspiración de los mejores del mundo",
    whileWeLoad: "✨ Mientras Cargamos...",
    freshMotivation: "💭 Motivación Fresca",
    selectPlayer: "Selecciona un jugador:",
    unnamed: "Sin Nombre",
    noTipsYet: "Aún no hay consejos personalizados.",
    createProfile: "¡Crea un perfil de jugador para obtener coaching con IA!",
    createPlayer: "➕ Crear Jugador",
    consultingAI: "Consultando al Entrenador IA...",
    errorTitle: "⚠️ ¡Ups!",
    tryAgain: "🔄 Intentar de Nuevo",
    back: "← Atrás"
  },
  fr: {
    addQuote: "Ajouter Votre Citation",
    yourName: "Votre Nom",
    yourQuote: "Votre Citation Inspirante",
    submit: "Soumettre",
    cancel: "Annuler",
    language: "Langue",
    selectLanguage: "Choisir la Langue",
    category: "Catégorie",
    filterByCategory: "Filtrer par Catégorie",
    all: "Toutes",
    football: "⚽ Football",
    basketball: "🏀 Basket-ball",
    tennis: "🎾 Tennis",
    boxing: "🥊 Boxe",
    athletics: "🏃 Athlétisme",
    gymnastics: "🤸 Gymnastique",
    coach: "👔 Entraîneur",
    business: "💼 Affaires",
    entertainment: "🎬 Divertissement",
    leadership: "👑 Leadership",
    wisdom: "📚 Sagesse",
    motivation: "🔥 Motivation",
    productivity: "⚡ Productivité",
    customQuotes: "📝 Vos Citations",
    noCustomQuotes: "Pas encore de citations personnalisées. Soyez le premier à inspirer!",
    profanityError: "Veuillez supprimer le langage inapproprié",
    emptyFieldsError: "Veuillez remplir tous les champs",
    successMessage: "Citation ajoutée avec succès!",
    refreshQuotes: "🔁 Plus d'Inspiration",
    dailyWisdom: "🌟 Sagesse Quotidienne du Football",
    inspirationFrom: "Inspiration des meilleurs au monde",
    whileWeLoad: "✨ Pendant le Chargement...",
    freshMotivation: "💭 Motivation Fraîche",
    selectPlayer: "Sélectionnez un joueur:",
    unnamed: "Sans Nom",
    noTipsYet: "Pas encore de conseils personnalisés.",
    createProfile: "Créez un profil de joueur pour obtenir un coaching IA!",
    createPlayer: "➕ Créer Joueur",
    consultingAI: "Consultation de l'IA Coach...",
    errorTitle: "⚠️ Oups!",
    tryAgain: "🔄 Réessayer",
    back: "← Retour"
  },
  pt: {
    addQuote: "Adicionar Sua Citação",
    yourName: "Seu Nome",
    yourQuote: "Sua Citação Inspiradora",
    submit: "Enviar",
    cancel: "Cancelar",
    language: "Idioma",
    selectLanguage: "Selecionar Idioma",
    category: "Categoria",
    filterByCategory: "Filtrar por Categoria",
    all: "Todas",
    football: "⚽ Futebol",
    basketball: "🏀 Basquete",
    tennis: "🎾 Tênis",
    boxing: "🥊 Boxe",
    athletics: "🏃 Atletismo",
    gymnastics: "🤸 Ginástica",
    coach: "👔 Treinador",
    business: "💼 Negócios",
    entertainment: "🎬 Entretenimento",
    leadership: "👑 Liderança",
    wisdom: "📚 Sabedoria",
    motivation: "🔥 Motivação",
    productivity: "⚡ Produtividade",
    customQuotes: "📝 Suas Citações",
    noCustomQuotes: "Ainda não há citações personalizadas. Seja o primeiro a inspirar!",
    profanityError: "Por favor remova linguagem inadequada",
    emptyFieldsError: "Por favor preencha todos os campos",
    successMessage: "Citação adicionada com sucesso!",
    refreshQuotes: "🔁 Mais Inspiração",
    dailyWisdom: "🌟 Sabedoria Diária do Futebol",
    inspirationFrom: "Inspiração dos melhores do mundo",
    whileWeLoad: "✨ Enquanto Carregamos...",
    freshMotivation: "💭 Motivação Fresca",
    selectPlayer: "Selecione um jogador:",
    unnamed: "Sem Nome",
    noTipsYet: "Ainda não há dicas personalizadas.",
    createProfile: "Crie um perfil de jogador para obter coaching com IA!",
    createPlayer: "➕ Criar Jogador",
    consultingAI: "Consultando o Treinador IA...",
    errorTitle: "⚠️ Ops!",
    tryAgain: "🔄 Tentar Novamente",
    back: "← Voltar"
  },
  ar: {
    addQuote: "أضف اقتباسك",
    yourName: "اسمك",
    yourQuote: "اقتباسك الملهم",
    submit: "إرسال",
    cancel: "إلغاء",
    language: "اللغة",
    selectLanguage: "اختر اللغة",
    category: "الفئة",
    filterByCategory: "تصفية حسب الفئة",
    all: "الكل",
    football: "⚽ كرة القدم",
    basketball: "🏀 كرة السلة",
    tennis: "🎾 التنس",
    boxing: "🥊 الملاكمة",
    athletics: "🏃 ألعاب القوى",
    gymnastics: "🤸 الجمباز",
    coach: "👔 مدرب",
    business: "💼 أعمال",
    entertainment: "🎬 ترفيه",
    leadership: "👑 قيادة",
    wisdom: "📚 حكمة",
    motivation: "🔥 تحفيز",
    productivity: "⚡ إنتاجية",
    customQuotes: "📝 اقتباساتك",
    noCustomQuotes: "لا توجد اقتباسات مخصصة بعد. كن الأول في الإلهام!",
    profanityError: "يرجى إزالة اللغة غير اللائقة",
    emptyFieldsError: "يرجى ملء جميع الحقول",
    successMessage: "تمت إضافة الاقتباس بنجاح!",
    refreshQuotes: "🔁 المزيد من الإلهام",
    dailyWisdom: "🌟 حكمة كرة القدم اليومية",
    inspirationFrom: "إلهام من الأفضل في العالم",
    whileWeLoad: "✨ بينما نحمّل...",
    freshMotivation: "💭 تحفيز جديد",
    selectPlayer: "اختر لاعباً:",
    unnamed: "بدون اسم",
    noTipsYet: "لا توجد نصائح مخصصة بعد.",
    createProfile: "أنشئ ملف لاعب للحصول على تدريب بالذكاء الاصطناعي!",
    createPlayer: "➕ إنشاء لاعب",
    consultingAI: "استشارة المدرب الذكي...",
    errorTitle: "⚠️ عذراً!",
    tryAgain: "🔄 حاول مرة أخرى",
    back: "← رجوع"
  },
  zh: {
    addQuote: "添加您的名言",
    yourName: "您的名字",
    yourQuote: "您的励志名言",
    submit: "提交",
    cancel: "取消",
    language: "语言",
    selectLanguage: "选择语言",
    category: "类别",
    filterByCategory: "按类别筛选",
    all: "全部",
    football: "⚽ 足球",
    basketball: "🏀 篮球",
    tennis: "🎾 网球",
    boxing: "🥊 拳击",
    athletics: "🏃 田径",
    gymnastics: "🤸 体操",
    coach: "👔 教练",
    business: "💼 商业",
    entertainment: "🎬 娱乐",
    leadership: "👑 领导力",
    wisdom: "📚 智慧",
    motivation: "🔥 激励",
    productivity: "⚡ 生产力",
    customQuotes: "📝 您的名言",
    noCustomQuotes: "还没有自定义名言。成为第一个激励他人的人！",
    profanityError: "请删除不当语言",
    emptyFieldsError: "请填写所有字段",
    successMessage: "名言添加成功！",
    refreshQuotes: "🔁 更多灵感",
    dailyWisdom: "🌟 每日足球智慧",
    inspirationFrom: "来自世界最佳的灵感",
    whileWeLoad: "✨ 加载中...",
    freshMotivation: "💭 新鲜激励",
    selectPlayer: "选择球员:",
    unnamed: "未命名",
    noTipsYet: "还没有个性化建议。",
    createProfile: "创建球员档案以获取AI教练指导！",
    createPlayer: "➕ 创建球员",
    consultingAI: "咨询AI教练...",
    errorTitle: "⚠️ 哎呀!",
    tryAgain: "🔄 重试",
    back: "← 返回"
  },
  de: {
    addQuote: "Zitat Hinzufügen",
    yourName: "Ihr Name",
    yourQuote: "Ihr Inspirierendes Zitat",
    submit: "Einreichen",
    cancel: "Abbrechen",
    language: "Sprache",
    selectLanguage: "Sprache Auswählen",
    category: "Kategorie",
    filterByCategory: "Nach Kategorie Filtern",
    all: "Alle",
    football: "⚽ Fußball",
    basketball: "🏀 Basketball",
    tennis: "🎾 Tennis",
    boxing: "🥊 Boxen",
    athletics: "🏃 Leichtathletik",
    gymnastics: "🤸 Gymnastik",
    coach: "👔 Trainer",
    business: "💼 Geschäft",
    entertainment: "🎬 Unterhaltung",
    leadership: "👑 Führung",
    wisdom: "📚 Weisheit",
    motivation: "🔥 Motivation",
    productivity: "⚡ Produktivität",
    customQuotes: "📝 Ihre Zitate",
    noCustomQuotes: "Noch keine benutzerdefinierten Zitate. Seien Sie der Erste, der inspiriert!",
    profanityError: "Bitte entfernen Sie unangemessene Sprache",
    emptyFieldsError: "Bitte füllen Sie alle Felder aus",
    successMessage: "Zitat erfolgreich hinzugefügt!",
    refreshQuotes: "🔁 Mehr Inspiration",
    dailyWisdom: "🌟 Tägliche Fußball-Weisheit",
    inspirationFrom: "Inspiration von den Besten der Welt",
    whileWeLoad: "✨ Während des Ladens...",
    freshMotivation: "💭 Frische Motivation",
    selectPlayer: "Spieler auswählen:",
    unnamed: "Unbenannt",
    noTipsYet: "Noch keine personalisierten Tipps.",
    createProfile: "Erstellen Sie ein Spielerprofil für AI-Coaching!",
    createPlayer: "➕ Spieler Erstellen",
    consultingAI: "AI-Trainer wird konsultiert...",
    errorTitle: "⚠️ Hoppla!",
    tryAgain: "🔄 Erneut Versuchen",
    back: "← Zurück"
  },
  it: {
    addQuote: "Aggiungi la Tua Citazione",
    yourName: "Il Tuo Nome",
    yourQuote: "La Tua Citazione Ispiratrice",
    submit: "Invia",
    cancel: "Annulla",
    language: "Lingua",
    selectLanguage: "Seleziona Lingua",
    category: "Categoria",
    filterByCategory: "Filtra per Categoria",
    all: "Tutte",
    football: "⚽ Calcio",
    basketball: "🏀 Pallacanestro",
    tennis: "🎾 Tennis",
    boxing: "🥊 Pugilato",
    athletics: "🏃 Atletica",
    gymnastics: "🤸 Ginnastica",
    coach: "👔 Allenatore",
    business: "💼 Affari",
    entertainment: "🎬 Intrattenimento",
    leadership: "👑 Leadership",
    wisdom: "📚 Saggezza",
    motivation: "🔥 Motivazione",
    productivity: "⚡ Produttività",
    customQuotes: "📝 Le Tue Citazioni",
    noCustomQuotes: "Nessuna citazione personalizzata ancora. Sii il primo a ispirare!",
    profanityError: "Si prega di rimuovere il linguaggio inappropriato",
    emptyFieldsError: "Si prega di compilare tutti i campi",
    successMessage: "Citazione aggiunta con successo!",
    refreshQuotes: "🔁 Altra Ispirazione",
    dailyWisdom: "🌟 Saggezza Quotidiana del Calcio",
    inspirationFrom: "Ispirazione dai migliori al mondo",
    whileWeLoad: "✨ Durante il Caricamento...",
    freshMotivation: "💭 Motivazione Fresca",
    selectPlayer: "Seleziona un giocatore:",
    unnamed: "Senza Nome",
    noTipsYet: "Nessun consiglio personalizzato ancora.",
    createProfile: "Crea un profilo giocatore per ottenere coaching AI!",
    createPlayer: "➕ Crea Giocatore",
    consultingAI: "Consultando l'AI Coach...",
    errorTitle: "⚠️ Ops!",
    tryAgain: "🔄 Riprova",
    back: "← Indietro"
  }
};

// 🚫 PROFANITY FILTER (Simple word list)
export const PROFANE_WORDS = [
  'damn', 'shit', 'fuck', 'bitch', 'ass', 'hell', 'crap', 'stupid', 'idiot', 'dumb',
  'bastard', 'piss', 'suck', 'damn', 'goddamn', 'fucking', 'bullshit', 'asshole'
];

export const containsProfanity = (text) => {
  const lowerText = text.toLowerCase();
  return PROFANE_WORDS.some(word => lowerText.includes(word));
};

// 🌐 SIMPLE TRANSLATOR (Dictionary-based for common phrases)
export const translateQuote = (quote, targetLang) => {
  if (targetLang === 'en') return quote;
  
  // Simple word replacement for demo (in production, use Google Translate API)
  const translations = {
    'en': { 'dream': 'dream', 'work': 'work', 'success': 'success', 'hard': 'hard' },
    'es': { 'dream': 'sueño', 'work': 'trabajo', 'success': 'éxito', 'hard': 'duro' },
    'fr': { 'dream': 'rêve', 'work': 'travail', 'success': 'succès', 'hard': 'dur' },
    'pt': { 'dream': 'sonho', 'work': 'trabalho', 'success': 'sucesso', 'hard': 'difícil' },
    // Add more as needed
  };
  
  let translated = quote;
  const dict = translations[targetLang] || translations['en'];
  
  Object.keys(dict).forEach(word => {
    const regex = new RegExp(`\\b${word}\\b`, 'gi');
    translated = translated.replace(regex, dict[word]);
  });
  
  return translated;
};

export default {
  MOTIVATIONAL_QUOTES,
  TRANSLATIONS,
  containsProfanity,
  translateQuote
};